
// This file has been generated by the GUI designer. Do not modify.
namespace datacapturer
{
	public partial class MainWindowCore
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget datacapturer.MainWindowCore
			global::Stetic.BinContainer.Attach (this);
			this.Name = "datacapturer.MainWindowCore";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
